export interface Lead {
  id?: string;
  name: string;
  college: string;
  source: string;
  deadline: string;
  budget: number;
  status: "New" | "Contacted" | "Interested" | "Negotiating" | "Booked" | "Lost";
  phone?: string;
  score: number;
  priorityScore?: number; // computed internally for sorting
  partnerSource?: string; // partner name/id if lead came from a partner
  lostReason?: string; // reason when status = Lost
  // timestamps
  createdAt: number;
  updatedAt?: number;
  lastContactedAt?: number;
  convertedAt?: number;
}

export interface OrderTimelineEvent {
  id: string;
  title: string;
  description?: string;
  status: "completed" | "current" | "upcoming";
  date: number;
}

export interface FileItem {
  id: string;
  name: string;
  url: string;
  size: number;
  type: string;
  uploadedAt: number;
  orderId: string;
  category?: "synopsis" | "report" | "source" | "receipt" | "other"; // auto-folder
}

export interface Order {
  id?: string;
  orderId: string;
  leadId?: string;
  clientName: string;
  college: string;
  topic: string;
  amount: number;
  amountPaid: number;
  status: "Booked" | "Synopsis" | "Development" | "Review" | "Final Payment" | "Delivered" | "Closed";
  deadline: string;
  timeline?: OrderTimelineEvent[];
  riskScore?: number;
  riskFlags?: string[]; // e.g. ["unpaid_near_deadline", "no_client_reply_5d"]
  clientNotes?: string;
  tasksLinked?: string[]; // array of task IDs
  partnerSource?: string;
  // timestamps
  createdAt: number;
  updatedAt?: number;
  statusChangedAt?: number;
  lastClientReplyAt?: number;
  deliveredAt?: number;
}

export interface Payment {
  id?: string;
  orderId: string;
  amount: number;
  method: string;
  note?: string;
  clientName: string;
  status: "Paid" | "Pending" | "Failed";
  isPartial?: boolean; // true if more balance remains
  remainingBalance?: number; // balance left after this payment
  // timestamps
  paidAt: number;
  updatedAt?: number;
}

export interface Partner {
  id?: string;
  name: string;
  college: string;
  phone: string;
  leadsSent: number;
  converted: number;
  commissionDue: number;
  trustScore: number;
  status: "Active" | "Inactive";
  rank?: number; // computed rank by performance
  inactiveDays?: number; // days since last lead
  // timestamps
  createdAt?: number;
  updatedAt?: number;
  lastLeadAt?: number; // timestamp of last lead sent
}

export interface Task {
  id: string;
  title: string;
  tags: string[];
  columnId: string; // 'today', 'urgent', 'waitingClient', 'done'
  createdAt: number;
  order: number;
  // smart task fields
  isAutoGenerated?: boolean; // true when created by workflow engine
  dueAt?: number; // optional due timestamp for smart reminders
  linkedOrderId?: string; // optional link to an order
  linkedLeadId?: string; // optional link to a lead
  updatedAt?: number;
}

export interface ActivityLog {
  id?: string;
  message: string;
  status: "new" | "success" | "pending" | "active" | "urgent";
  timestamp: number;
  type: string;
  targetId?: string; // ID of the linked entity (lead, order, etc.)
  meta?: Record<string, unknown>; // optional extra context
}

export interface WhatsAppTemplate {
  id: string;
  name: string;
  text: string;
}

export interface AppSettings {
  id?: string;
  pricingTiers: { name: string; price: number }[];
  defaultBookingAmount: number;
  whatsappTemplates: WhatsAppTemplate[];
  webhookUrls: { name: string; url: string }[];
  founderProfile: { name: string; email: string; phone: string };
  seasonModeEnabled: boolean;
  seasonStart?: string; // ISO date string e.g. "2025-01-01"
  seasonEnd?: string; // ISO date string e.g. "2025-05-31"
  commissionSlabs: { minLeads: number; maxLeads: number; percentage: number }[];
  themePreferences: { primaryColor: string; darkMode: boolean };
  // new operational settings
  paymentReminderDays: number; // flag payment overdue after X days
  defaultTaskTimings: {
    followUpHours: number; // hours after Contacted → Interested to remind
    synopsisDueHours: number; // hours after Synopsis status to create task
    progressCheckDays: number; // days after Development status to check
  };
}
