/**
 * workflow.ts — Central Workflow Engine for LOVE
 *
 * All status-change side-effects live here. Pages call these functions
 * instead of doing raw DB writes so logic is centralized and reusable.
 */

import { db } from "@/lib/firebase";
import {
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  query,
  updateDoc,
  where,
  writeBatch,
} from "firebase/firestore";
import { Lead, Order, Partner, Task } from "./types";
import { logActivity } from "./activity";

// ─────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────

/** Generate a short random order ID */
export const generateOrderId = () =>
  `ORD-${Math.floor(1000 + Math.random() * 9000)}`;

/** Create an auto-generated task in Firestore */
export const createAutoTask = async (
  title: string,
  columnId: "today" | "urgent" | "waitingClient" | "done",
  tags: string[],
  options?: {
    linkedOrderId?: string;
    linkedLeadId?: string;
    dueAt?: number; // epoch ms
  }
): Promise<string> => {
  const colTasks = await getDocs(
    query(collection(db, "tasks"), where("columnId", "==", columnId))
  );
  const order = colTasks.size;

  const taskData: Omit<Task, "id"> = {
    title,
    columnId,
    tags,
    createdAt: Date.now(),
    order,
    isAutoGenerated: true,
    ...(options?.linkedOrderId && { linkedOrderId: options.linkedOrderId }),
    ...(options?.linkedLeadId && { linkedLeadId: options.linkedLeadId }),
    ...(options?.dueAt && { dueAt: options.dueAt }),
  };

  const ref = await addDoc(collection(db, "tasks"), taskData);
  return ref.id;
};

/** Compute risk flags for an order */
export const computeOrderRiskFlags = (
  order: Order,
  now: Date = new Date()
): string[] => {
  const flags: string[] = [];

  // Unpaid + deadline within 3 days
  if (order.amount > order.amountPaid && order.deadline) {
    const deadlineDiff =
      (new Date(order.deadline).getTime() - now.getTime()) /
      (1000 * 60 * 60 * 24);
    if (deadlineDiff <= 3 && deadlineDiff >= 0) {
      flags.push("unpaid_near_deadline");
    }
  }

  // No client reply in 5 days
  if (order.lastClientReplyAt) {
    const noReplyDays =
      (now.getTime() - order.lastClientReplyAt) / (1000 * 60 * 60 * 24);
    if (noReplyDays >= 5) {
      flags.push("no_client_reply_5d");
    }
  }

  // Too many status delays (created > 14 days ago, not delivered/closed)
  if (
    order.status !== "Delivered" &&
    order.status !== "Closed" &&
    order.createdAt
  ) {
    const ageDays =
      (now.getTime() - order.createdAt) / (1000 * 60 * 60 * 24);
    if (ageDays > 14) {
      flags.push("status_delay");
    }
  }

  return flags;
};

/** Compute enhanced lead priority score */
export const computeLeadPriorityScore = (lead: Partial<Lead>): number => {
  let score = 50;

  // Source bonus
  if (
    lead.source?.toLowerCase().includes("partner") ||
    lead.source?.toLowerCase().includes("referral") ||
    lead.partnerSource
  )
    score += 20;

  // Budget
  const budgetVal =
    typeof lead.budget === "number"
      ? lead.budget
      : Number(
        (lead.budget as unknown as string)?.replace(/[^0-9]/g, "") || 0
      );
  if (budgetVal > 5000) score += 20;
  else if (budgetVal > 2000) score += 10;
  else if (budgetVal < 500) score -= 10;

  // Recent contact
  if (lead.lastContactedAt) {
    const minutesSince =
      (Date.now() - lead.lastContactedAt) / (1000 * 60);
    if (minutesSince < 60) score += 15; // contacted in last hour
  }

  // Urgent deadline
  if (lead.deadline) {
    const deadlineDays =
      (new Date(lead.deadline).getTime() - Date.now()) / (1000 * 60 * 60 * 24);
    if (deadlineDays <= 3 && deadlineDays >= 0) score += 15;
  }

  // Status penalties
  if (lead.status === "Lost") score -= 30;
  if (lead.status === "Booked") score = 100;
  if (lead.status === "Negotiating") score += 10;

  return Math.min(100, Math.max(0, score));
};

// ─────────────────────────────────────────────────────────
// LEAD WORKFLOW
// ─────────────────────────────────────────────────────────

/**
 * Fire side-effects when a lead status changes.
 * Called from leads/page.tsx instead of raw update().
 */
export const onLeadStatusChange = async (
  lead: Lead,
  newStatus: Lead["status"],
  lostReason?: string,
  taskTimings = { followUpHours: 2 }
): Promise<void> => {
  const now = Date.now();
  const updates: Partial<Lead> = {
    status: newStatus,
    updatedAt: now,
    priorityScore: computeLeadPriorityScore({ ...lead, status: newStatus }),
  };

  if (newStatus === "Contacted") {
    updates.lastContactedAt = now;
    await logActivity(
      `${lead.name} marked as Contacted`,
      "active",
      "lead_status",
      lead.id
    );
  }

  if (newStatus === "Interested") {
    // Create follow-up task
    await createAutoTask(
      `Follow-up: ${lead.name} (Interested)`,
      "today",
      ["follow-up", "lead"],
      {
        linkedLeadId: lead.id,
        dueAt: now + taskTimings.followUpHours * 60 * 60 * 1000,
      }
    );
    await logActivity(
      `${lead.name} is Interested — follow-up task created`,
      "new",
      "lead_status",
      lead.id
    );
  }

  if (newStatus === "Negotiating") {
    await logActivity(
      `${lead.name} in Negotiation — suggest sending a quote`,
      "pending",
      "lead_status",
      lead.id
    );
  }

  if (newStatus === "Lost") {
    updates.lostReason = lostReason || "Unknown";
    await logActivity(
      `Lead ${lead.name} marked Lost — reason: ${lostReason || "Unknown"}`,
      "pending",
      "lead_status",
      lead.id
    );
  }

  // Apply updates to Firestore
  if (lead.id) {
    await updateDoc(doc(db, "leads", lead.id), updates as any);
  }
};

/**
 * Convert a lead to an order (Negotiating → Booked flow).
 * Returns the new order ID string.
 */
export const convertLeadToOrder = async (
  lead: Lead
): Promise<string> => {
  const now = Date.now();
  const orderId = generateOrderId();

  // Update lead
  if (lead.id) {
    await updateDoc(doc(db, "leads", lead.id), {
      status: "Booked",
      score: 100,
      priorityScore: 100,
      convertedAt: now,
      updatedAt: now,
    });
  }

  // Create order
  const orderData = {
    orderId,
    leadId: lead.id || "",
    clientName: lead.name,
    college: lead.college,
    topic: "TBD",
    amount:
      typeof lead.budget === "number"
        ? lead.budget
        : Number(
          (lead.budget as unknown as string)?.replace(/[^0-9]/g, "") || 0
        ),
    amountPaid: 0,
    status: "Booked",
    deadline: lead.deadline,
    partnerSource: lead.partnerSource || "",
    createdAt: now,
    updatedAt: now,
    statusChangedAt: now,
    riskFlags: [],
  };

  await addDoc(collection(db, "orders"), orderData);

  // Create onboarding tasks
  const batch = writeBatch(db);
  const onboardingTasks = [
    {
      title: `Create WA Group for ${lead.name}`,
      columnId: "today",
      tags: ["onboarding", "comms"],
    },
    {
      title: `Send Welcome Message to ${lead.name}`,
      columnId: "today",
      tags: ["onboarding", "comms"],
    },
    {
      title: `Collect Advance for ${orderId}`,
      columnId: "urgent",
      tags: ["onboarding", "finance"],
    },
  ];
  onboardingTasks.forEach((t, i) => {
    const ref = doc(collection(db, "tasks"));
    batch.set(ref, {
      ...t,
      id: ref.id,
      createdAt: now,
      order: i,
      isAutoGenerated: true,
      linkedOrderId: orderId,
    });
  });
  await batch.commit();

  // Update partner stats if lead came from a partner
  if (lead.partnerSource) {
    await incrementPartnerConversion(lead.partnerSource);
  }

  await logActivity(
    `Lead ${lead.name} converted to Order #${orderId}. Onboarding started.`,
    "success",
    "conversion",
    lead.id
  );

  return orderId;
};

/** Detect if a phone already exists in leads */
export const checkDuplicatePhone = async (
  phone: string
): Promise<Lead | null> => {
  if (!phone || phone.trim() === "") return null;
  try {
    const q = query(
      collection(db, "leads"),
      where("phone", "==", phone.trim())
    );
    const snap = await getDocs(q);
    if (!snap.empty) {
      return { id: snap.docs[0].id, ...snap.docs[0].data() } as Lead;
    }
  } catch {
    // Ignore errors silently
  }
  return null;
};

// ─────────────────────────────────────────────────────────
// ORDER WORKFLOW
// ─────────────────────────────────────────────────────────

const ORDER_STATUS_TASK_MAP: Record<
  Order["status"],
  {
    title: (o: Order) => string;
    column: "today" | "urgent" | "waitingClient";
    tags: string[];
    dueOffsetHours: number;
  } | null
> = {
  Booked: null, // handled by convertLeadToOrder
  Synopsis: {
    title: (o) => `Send Synopsis for ${o.orderId} (${o.clientName})`,
    column: "urgent",
    tags: ["synopsis", "delivery"],
    dueOffsetHours: 24,
  },
  Development: {
    title: (o) => `Progress check: ${o.orderId} — ${o.clientName}`,
    column: "today",
    tags: ["progress", "dev"],
    dueOffsetHours: 72,
  },
  Review: {
    title: (o) => `Get client feedback: ${o.orderId} — ${o.clientName}`,
    column: "waitingClient",
    tags: ["review", "client"],
    dueOffsetHours: 48,
  },
  "Final Payment": {
    title: (o) => `Collect final payment for ${o.orderId} — ${o.clientName}`,
    column: "urgent",
    tags: ["payment", "collection"],
    dueOffsetHours: 24,
  },
  Delivered: {
    title: (o) => `Request testimonial from ${o.clientName} (${o.orderId})`,
    column: "today",
    tags: ["testimonial", "post-delivery"],
    dueOffsetHours: 48,
  },
  Closed: null,
};

/**
 * Fire side-effects when an order status changes.
 */
export const onOrderStatusChange = async (
  order: Order,
  newStatus: Order["status"]
): Promise<void> => {
  const now = Date.now();
  const updates: Partial<Order> = {
    status: newStatus,
    updatedAt: now,
    statusChangedAt: now,
  };

  if (newStatus === "Delivered") {
    updates.deliveredAt = now;
  }

  if (newStatus === "Closed") {
    await logActivity(
      `Order ${order.orderId} closed and archived.`,
      "success",
      "order_status",
      order.id
    );
  }

  const taskSpec = ORDER_STATUS_TASK_MAP[newStatus];
  if (taskSpec) {
    await createAutoTask(taskSpec.title(order), taskSpec.column, taskSpec.tags, {
      linkedOrderId: order.orderId,
      dueAt: now + taskSpec.dueOffsetHours * 60 * 60 * 1000,
    });
    await logActivity(
      `Order ${order.orderId} moved to ${newStatus} — auto-task created.`,
      "new",
      "order_status",
      order.id
    );
  }

  // Compute and save risk flags
  const riskFlags = computeOrderRiskFlags({ ...order, ...updates } as Order);
  updates.riskFlags = riskFlags;

  if (order.id) {
    await updateDoc(doc(db, "orders", order.id), updates as any);
  }
};

// ─────────────────────────────────────────────────────────
// PARTNER WORKFLOW
// ─────────────────────────────────────────────────────────

/** Increment partner's leadsSent count when a lead is attributed */
export const incrementPartnerLeadsSent = async (
  partnerName: string
): Promise<void> => {
  const q = query(
    collection(db, "partners"),
    where("name", "==", partnerName)
  );
  const snap = await getDocs(q);
  if (snap.empty) return;
  const partnerDoc = snap.docs[0];
  const partner = partnerDoc.data() as Partner;
  await updateDoc(doc(db, "partners", partnerDoc.id), {
    leadsSent: (partner.leadsSent || 0) + 1,
    lastLeadAt: Date.now(),
    updatedAt: Date.now(),
  });
};

/** Increment partner's converted count + auto-commission calculation */
export const incrementPartnerConversion = async (
  partnerName: string
): Promise<void> => {
  try {
    // Get commission slabs from settings
    const settingsSnap = await getDoc(doc(db, "settings", "global"));
    const settings = settingsSnap.exists() ? settingsSnap.data() : null;
    const commissionSlabs: { minLeads: number; maxLeads: number; percentage: number }[] =
      settings?.commissionSlabs || [{ minLeads: 1, maxLeads: 999, percentage: 10 }];

    const q = query(
      collection(db, "partners"),
      where("name", "==", partnerName)
    );
    const snap = await getDocs(q);
    if (snap.empty) return;

    const partnerDoc = snap.docs[0];
    const partner = partnerDoc.data() as Partner;
    const newConverted = (partner.converted || 0) + 1;

    // Find applicable commission slab
    const slab = commissionSlabs.find(
      (s) => newConverted >= s.minLeads && newConverted <= s.maxLeads
    ) || commissionSlabs[commissionSlabs.length - 1];

    // Commission on the converted lead (estimated ₹1000 base if no order amount available)
    const commissionAmount = (1000 * (slab?.percentage || 10)) / 100;

    await updateDoc(doc(db, "partners", partnerDoc.id), {
      converted: newConverted,
      commissionDue: (partner.commissionDue || 0) + commissionAmount,
      updatedAt: Date.now(),
    });
  } catch (e) {
    console.error("Failed to increment partner conversion:", e);
  }
};

/**
 * Compute inactive days for all partners and update their status.
 * Call this on partner page load.
 */
export const refreshPartnerInactivity = async (): Promise<void> => {
  try {
    const snap = await getDocs(collection(db, "partners"));
    const now = Date.now();
    const batch = writeBatch(db);
    let i = 0;

    snap.docs.forEach((docSnap) => {
      const partner = docSnap.data() as Partner;
      const lastActivity = partner.lastLeadAt || partner.createdAt || now;
      const inactiveDays = Math.floor(
        (now - lastActivity) / (1000 * 60 * 60 * 24)
      );
      const newStatus: Partner["status"] =
        inactiveDays >= 10 ? "Inactive" : "Active";

      batch.update(doc(db, "partners", docSnap.id), {
        inactiveDays,
        status: newStatus,
        updatedAt: now,
      });
      i++;
    });

    if (i > 0) await batch.commit();
  } catch (e) {
    console.error("Failed to refresh partner inactivity:", e);
  }
};

// ─────────────────────────────────────────────────────────
// SMART REMINDER ENGINE
// ─────────────────────────────────────────────────────────

/**
 * Run all smart reminder checks and create tasks where needed.
 * Call this once per session / on dashboard load.
 */
export const runSmartReminderEngine = async (): Promise<number> => {
  let tasksCreated = 0;
  const now = Date.now();

  try {
    // 1. New lead not contacted in 30 mins
    const leadsSnap = await getDocs(collection(db, "leads"));
    for (const d of leadsSnap.docs) {
      const lead = { id: d.id, ...d.data() } as Lead;
      if (
        lead.status === "New" &&
        now - lead.createdAt > 30 * 60 * 1000
      ) {
        // Check if reminder task already exists
        const existing = await getDocs(
          query(
            collection(db, "tasks"),
            where("linkedLeadId", "==", lead.id),
            where("tags", "array-contains", "reminder-uncontacted")
          )
        );
        if (existing.empty) {
          await createAutoTask(
            `Call new lead: ${lead.name} (${lead.phone || "no phone"})`,
            "urgent",
            ["reminder-uncontacted", "lead", "call"],
            { linkedLeadId: lead.id }
          );
          tasksCreated++;
        }
      }

      // 2. Interested lead idle 24h
      if (
        lead.status === "Interested" &&
        lead.updatedAt &&
        now - lead.updatedAt > 24 * 60 * 60 * 1000
      ) {
        const existing = await getDocs(
          query(
            collection(db, "tasks"),
            where("linkedLeadId", "==", lead.id),
            where("tags", "array-contains", "reminder-interested-idle")
          )
        );
        if (existing.empty) {
          await createAutoTask(
            `Re-engage interested lead: ${lead.name}`,
            "today",
            ["reminder-interested-idle", "follow-up"],
            { linkedLeadId: lead.id }
          );
          tasksCreated++;
        }
      }
    }

    // 3. Payment pending 2 days
    const ordersSnap = await getDocs(collection(db, "orders"));
    for (const d of ordersSnap.docs) {
      const order = { id: d.id, ...d.data() } as Order;
      const twoDaysAgo = now - 2 * 24 * 60 * 60 * 1000;
      if (
        order.amount > order.amountPaid &&
        order.createdAt < twoDaysAgo &&
        order.status !== "Closed" &&
        order.status !== "Delivered"
      ) {
        const existing = await getDocs(
          query(
            collection(db, "tasks"),
            where("linkedOrderId", "==", order.orderId),
            where("tags", "array-contains", "reminder-payment-pending")
          )
        );
        if (existing.empty) {
          await createAutoTask(
            `Collect payment: ${order.orderId} — ${order.clientName} (₹${order.amount - order.amountPaid} pending)`,
            "urgent",
            ["reminder-payment-pending", "payment"],
            { linkedOrderId: order.orderId }
          );
          tasksCreated++;
        }
      }

      // 4. Deadline in 3 days
      if (order.deadline && order.status !== "Delivered" && order.status !== "Closed") {
        const deadlineDiff =
          (new Date(order.deadline).getTime() - now) / (1000 * 60 * 60 * 24);
        if (deadlineDiff <= 3 && deadlineDiff >= 0) {
          const existing = await getDocs(
            query(
              collection(db, "tasks"),
              where("linkedOrderId", "==", order.orderId),
              where("tags", "array-contains", "reminder-deadline")
            )
          );
          if (existing.empty) {
            await createAutoTask(
              `Deadline in ${Math.ceil(deadlineDiff)}d: ${order.orderId} — ${order.topic}`,
              "urgent",
              ["reminder-deadline", "urgent"],
              { linkedOrderId: order.orderId }
            );
            tasksCreated++;
          }
        }
      }
    }

    // 5. Partner inactive 7 days
    const partnersSnap = await getDocs(collection(db, "partners"));
    for (const d of partnersSnap.docs) {
      const partner = { id: d.id, ...d.data() } as Partner;
      const lastActivity = partner.lastLeadAt || partner.createdAt || now;
      const inactiveDays = (now - lastActivity) / (1000 * 60 * 60 * 24);
      if (inactiveDays >= 7) {
        const existing = await getDocs(
          query(
            collection(db, "tasks"),
            where("tags", "array-contains", `reminder-partner-${partner.id}`)
          )
        );
        if (existing.empty) {
          await createAutoTask(
            `Follow up with inactive partner: ${partner.name}`,
            "today",
            [`reminder-partner-${partner.id}`, "partner", "inactive"],
          );
          tasksCreated++;
        }
      }
    }
  } catch (e) {
    console.error("Smart reminder engine error:", e);
  }

  return tasksCreated;
};
